FROM python:3.10-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    git \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --upgrade pip

COPY pyproject.toml /app/

COPY src /app/src/

RUN pip install -e .[dev]

COPY . /app/

CMD ["python", "-m", "deepkernels.main"]