
services:
  sandbox:
    container_name: deepkernels-playground
    build:
      context: .
      dockerfile: Dockerfile.public
    ports:
      - "8888:8888"
    volumes:
      - .:/app 
    environment:
      - JUPYTER_ENABLE_LAB=yes
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu, compute, utility]
    shm_size: '2gb'