name: Vultr Production Deploy

# This tells the robot to only run when you push to the 'main' branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH into Vultr and Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VULTR_IP }}
          username: ${{ secrets.VULTR_USER }}
          key: ${{ secrets.VULTR_SSH_KEY }}
          script: |
            cd ~/deepkernels/deepkernelsroot
            git pull origin main
            docker-compose up -d --build
            docker image prune -f