import torch
import gpytorch
from torch.distributions import Normal, TransformedDistribution, kl_divergence, Dirichlet
from torch.distributions.transforms import StickBreakingTransform
import math

import torch.nn as nn
import torch.nn.functional as F
from pydantic import BaseModel
from typing import Tuple, Optional, TypeAlias, Tuple, Union
from gpytorch.mlls import AddedLossTerm
import logging

from deepkernels.models.parent import BaseGenerativeModel
from deepkernels.losses.simple import SimpleLoss

#---Init logger---#
logger = logging.getLogger(__name__)
if not logger.handlers:
    logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')

class HDPConfig(BaseModel):
    K: int = 30
    M: int = 128
    D: int = 16
    eps: float = 1e-3
    gamma_init: float = 1.75
    mu_init: float = 0.0
    sigma_init: float = 1.0
    num_inducing: int = 1024
    sigma_q_init: float = 1.5
    sigma_h_init: float = 1.0
    atom_factor: float = 0.0075


class AmortisedDirichlet(BaseGenerativeModel):
    def __init__(self, 
                 config=None, 
                 k_atoms=30, 
                 fourier_dim=128, 
                 latent_dim=16, 
                 spectral_emb_dim=2048):
        self.config = config or HDPConfig()
        self.n_data = 38003
        self.K = k_atoms or self.config.K
        self.M = fourier_dim or self.config.M #-rff samples per mixture-#
        self.D = latent_dim or self.config.D #-input dim-#
        self.eps = 1e-3

        self.compress_spectral_features_head = torch.nn.utils.spectral_norm(nn.Linear(k_atoms * fourier_dim * 2, spectral_emb_dim))
        
        input_dim = 30
        latent_dim = 16

        #--init constraints--#
        self.mu_init = self.config.mu_init or 0.0
        self.sigma_init = self.config.sigma_init or 1.0
        self.log_sigma_init = math.log(self.sigma_init)
        self.sigma_q_init = self.config.sigma_q_init or 1.5
        self.qsig = (math.log(self.sigma_q_init)) * -1.0
        self.sigma_h_init = self.config.sigma_h_init or 1.0
        self.hsig = (math.log(self.sigma_h_init)) * -1.0
        self.atom_factor = self.config.atom_factor or 0.0075

        # ---------------------------------------------------------
        # Structure: GEM Global Mixing Weights (Beta)
        # ---------------------------------------------------------
        #-- variational params - q(v) ~ N(q_mu, q_log_sigma)
        self.q_mu = nn.Parameter(torch.full((self.K - 1,), -2.0)) #--break symmetry-#
        self.q_log_sigma = nn.Parameter(torch.full((self.K - 1,), -4.0)) # or self.qsig if you have it defined#-cluster stability-#

        # ---------------------------------------------------------
        # Content: Spectral Frequencies (Omega)
        # ---------------------------------------------------------
        #--spectral mixture kernel: defined by weight (pi), center (atom_mu), width (atom_log_scale)

        #--Global Base Distribution (H) defines kernel smoothness & freq
        self.h_mu = nn.Parameter(torch.zeros(1, 1, input_dim)) #-center of kernels -- mu prior on gram matrix-#
        self.h_log_sigma = nn.Parameter(torch.tensor(self.hsig)) #-global bandwidth-#

        #-local atom deviation (additive)-#
        self.atom_log_sigma = nn.Parameter(torch.zeros(1, fourier_dim, input_dim) * math.sqrt(self.atom_factor))
        self.atom_mu = nn.Parameter(torch.randn(self.K, 1, input_dim) * self.atom_factor)

        #--RFF Constants - fixed noise params--#
        #-draw standard normal once and freeze (fundamental random fourier projection assumption)--#
        self.register_buffer("noise_weights", torch.randn(self.K, self.M, input_dim)) #-Shape: [K, M, D]-#
        self.register_buffer("noise_bias", torch.rand(self.K, self.M) * 2 * math.pi)

        # ---------------------------------------------------------
        # C) Concentration (Gamma)
        # ---------------------------------------------------------
        #-- Learnable scalar for dirichlet process concentration (gamma)-#
        self.gamma_init = 2.0
        self.gamma = nn.Parameter(torch.tensor(float(self.gamma_init)))

        #--Define torch stickbreak module-#
        self.stick_break_transform = StickBreakingTransform()

        super().__init__()
    
    def dynamic_random_fourier_features(self, z: torch.Tensor, omega: torch.Tensor, pi: Optional[torch.Tensor]=None):
        """
        Args:
            z: [Batch, D]
            omega: [Batch, K, M, D] (dynamic) - generated by get_omega
            pi: [B, K] 
        """
        B, D = z.shape
        if pi is None:
            pi = torch.full((B, self.K), 1.0/self.K, device=z.device)
            pi = pi + (torch.randn_like(pi) * 0.01)
            pi = F.softmax(pi, dim=-1)
        
        #-determine if omega is dynamic-#
        if omega.dim() == 4:
            #-Dynamic: [B, K, M, D] * [B, 1, 1, D] -> Sum over D -#
            proj = (z.view(B, 1, 1, D) * omega).sum(dim=-1) #-dynamic-# z -> [B,1 ,1, D]
        else:
            W = omega.view(-1, D)
            proj = F.linear(z, W) #-static-#
            proj = proj.view(B, self.K, self.M)
        
        #-phase shift-#
        proj = proj + self.noise_bias.unsqueeze(0) #- [K, M] -> [1, K, M]
        
        #-scale for vae-#
        scale = 1.0 / math.sqrt(self.M)
        
        #-harmonics-#
        cos_proj = torch.cos(proj) * scale
        sin_proj = torch.sin(proj) * scale

        #-Mixing weights (amortised)-#
        #-unsqueeze [B, K] -> [B, K, 1]
        pi_scl = torch.sqrt(pi).unsqueeze(-1)
        cos_proj = cos_proj * pi_scl
        sin_proj = sin_proj * pi_scl
        
        feats = torch.stack([cos_proj, sin_proj], dim=-1) #- [B, K, M] -> [B, K, M, 2]

        return feats.flatten(1) #-[B, (K * M * 2)]
    
    def get_omega(self, ls_pred=None):
        """
        Generates the Spectral Frequencies (Omega) for the current batch.
        
        Logic: Omega ~ N(mu_global + mu_local, sigma_global + sigma_local * ls_dynamic)
        
        Args:
            ls_pred: [Batch, K, D] (Optional) - Amortised lengthscales from VAE.
                     If None, uses the learned prior (static kernel).
        Returns:
            omega: [Batch, K, M, D] - The frequency set for every atom in every image.
        """

        #-h_mu (Global) + atom_mu (Local Cluster Center)
        #-Shape: [1, 1, D] + [K, 1, D] = [K, 1, D]
        means = self.h_mu + self.atom_mu 
        
        # Broadcast to [1, K, 1, D] for batch compatibility
        means_expanded = means.unsqueeze(0) 

        # ---------------------------------------------------------
        # 2. Compute The Bandwidth / Variance (Hierarchical)
        # ---------------------------------------------------------
        log_scale = self.h_log_sigma + self.atom_log_sigma
        bw_base = F.softplus(log_scale) # Shape: [K, 1, D]
        
        # B) Dynamic Scaling (Amortised Inference)
        if ls_pred is not None:
            # ls_pred: [Batch, K, D]
            ls_inv = 1.0 / (ls_pred + 1e-6) 
            
            # Combine: [1, K, 1, D] * [Batch, K, 1, D]
            bw_dynamic = bw_base.unsqueeze(0) * ls_inv.unsqueeze(2)
        else:
            # Static Mode: Just use the base learned width
            bw_dynamic = bw_base.unsqueeze(0) # [1, K, 1, D]
        
        # noise_weights: [K, M, D] -> [1, K, M, D]
        noise_expanded = self.noise_weights.unsqueeze(0)
        
        # [1, K, 1, D] + ([Batch, K, 1, D] * [1, K, M, D])
        omega_unclamped = means_expanded + (bw_dynamic * noise_expanded)
        omega = torch.clamp(omega_unclamped, -100.0, 100.0)
        return omega #-[Batch, K_atoms, M_modes, D_dim]-#
        

    def forward(self, 
            z, 
            batch_shape=torch.Size([]), 
            ls: Optional[torch.Tensor]=None, 
            alpha: Optional[torch.Tensor]=None):
        """
        Args:
            z: [Batch, D] - Latent (Required for features)
            alpha_amortised: [Batch, K] - Dirichlet Concentration (from Encoder)
            ls_amortised: [Batch, K, D] - Lengthscales (from Encoder or Override)
        """
        
        # ---------------------------------------------------------
        # 1. Global Variational Inference (Stick Breaking)
        # ---------------------------------------------------------
        #--A) define variational posterior - q(v)-#
        q_sig = F.softplus(self.q_log_sigma)
        q_dist = Normal(self.q_mu, q_sig)
        
        #-loss for q-#
        #-sample from logit space-#
        qz_global = q_dist.rsample()
        
        # -- B) Calculate Analytic KL Terms via Softplus --
        #-- Log Posterior q(v) --#
        # log q(v) = log q(z) - log |det J|
        # log |det J| = log(v(1-v)) = -softplus(-z) - softplus(z)
        log_detj = -F.softplus(-qz_global) - F.softplus(qz_global)
        log_qv = q_dist.log_prob(qz_global).sum(-1) - log_detj.sum(-1)

        # 2. Log Prior p(v) ~ Beta(1, gamma)
        # log p(v) = log(gamma) + (gamma - 1) * log(1 - v)
        # Using identity: log(1 - sigmoid(z)) = -softplus(z)
        gamma = F.softplus(self.gamma)
        log_pv = (torch.log(gamma + self.eps) + (gamma - 1) * (-F.softplus(qz_global))).sum(-1)

        # 3. KL Divergence (Monte Carlo Estimate)
        # KL = E[log q(v) - log p(v)]
        global_divergence = (log_qv - log_pv).sum()

        self.update_added_loss_term("global_divergence", SimpleLoss(global_divergence))

        # -- Compute Mixture Weights (beta) for downstream use --
        # Transform z -> v -> beta (stick breaking)
        qv_global = torch.sigmoid(qz_global)
        one_minus_v = 1 - qv_global
        cumprod_one_minus_v = torch.cumprod(one_minus_v, dim=-1)
        previous_remaining = torch.roll(cumprod_one_minus_v, 1, dims=-1)
        previous_remaining[..., 0] = 1.0
        beta_k = qv_global * previous_remaining
        beta_last = cumprod_one_minus_v[..., -1:]
        beta = torch.cat([beta_k, beta_last], dim=-1)

        # ---------------------------------------------------------
        # 2. Local Concentration (Prior vs Posterior)
        # ---------------------------------------------------------
        prior_conc = (gamma * beta) + self.eps
        prior_conc = torch.clamp(prior_conc, min=1e-2, max=100.0)
        ls_pred = None
        #--E) amortised inference--#
        if z is not None:
            batch_size = z.size(0)
            prior_conc_expanded = prior_conc.unsqueeze(0).expand(batch_size, -1) #-[K] -> [1, K] -> [B, K]-#
        else:
            if len(batch_shape) > 0:
                view_shape = [1] * len(batch_shape) + [-1] 
                prior_reshaped = prior_conc.view(*view_shape)
                prior_conc_expanded = prior_reshaped.expand(*batch_shape, -1)
            else:
                prior_conc_expanded = prior_conc.unsqueeze(0)
        
        if alpha is not None:
            #--amortised inference in training-#
            #-Data evidence from neural net (pi_encoder)-#
            #- z: [B, D] -> data_conc: [B, K]-#
            
            #-posterior = prior + local evidence-#
            local_conc = torch.clamp(alpha, min=self.eps, max=100.0)
            post_conc = prior_conc_expanded + local_conc
            post_conc = torch.clamp(post_conc, min=self.eps, max=100.0)
            
            #-KL Posterior-#
            #-Create Distribution objects for kl loss updates-#
            pr_dist_pi = Dirichlet(prior_conc_expanded) #-[B, K]
            post_dist_pi = Dirichlet(post_conc) #-- [B, K]
            local_divergence = torch.distributions.kl_divergence(post_dist_pi, pr_dist_pi)
            self.update_added_loss_term("local_divergence", SimpleLoss(local_divergence.sum()))
            
            if ls is not None:
                ls_pred = torch.clamp(ls, min=self.eps, max=50.0) #- [B, K, D]
                target_ls = torch.tensor(1.0, device=ls_pred.device)
                ls_log_mse = F.mse_loss(torch.log(ls_pred), torch.log(target_ls.expand_as(ls_pred)))
                self.update_added_loss_term("spectral_mse_loss", SimpleLoss(ls_log_mse))
        else:
            # --- GENERATIVE MODE ---
            # No evidence provided. We sample from the Prior.
            post_conc = prior_conc_expanded #-kl will be 0-#

        #--Sample from pi (dynamic)-#
        pi = Dirichlet(post_conc).rsample() #--[B, K]-#

        omega_frequencies = self.get_omega(ls_pred) #-[B, K, M, D]-#

        features = self.dynamic_random_fourier_features(z, omega_frequencies)

        kernel_features_projection = self.compress_spectral_features_head(features)
        
        return kernel_features_projection